// =============================================================================
// reasoning/run.mjs — dataset pass-through (CLI entrypoint)
// =============================================================================
//
// How any future dataset enters the interpretation engine:
//
//   node reasoning/run.mjs [path/to/ontology_layer.json]
//
// Default input: collect/output/ontology/ontology_layer.json (the current
// data-driven ontology). The runner:
//   1. loads the ontology dataset,
//   2. passes it through the engine (AI detection + human scaffolds),
//   3. asserts the Human–AI boundary on every record,
//   4. generates the research manifest, and
//   5. writes three artifacts to reasoning/output/:
//        interpretation.json   — the full record set
//        research-manifest.json — per-rung readiness + Rung-1 body
//        human-worksheet.md     — the significance a human must supply
//
// The engine is offline and analysis-only. Like collect/, it never touches
// the website build.
// =============================================================================

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { interpret } from "./engine.mjs";
import { generateResearch } from "./generate.mjs";
import { LADDER, LENSES, OUTPUT_GATE } from "./architecture.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const DEFAULT_INPUT = resolve(ROOT, "collect/output/ontology/ontology_layer.json");
const OUT_DIR = resolve(HERE, "output");

function loadOntology(path) {
  const raw = JSON.parse(readFileSync(path, "utf8"));
  if (!raw.concepts || !raw.edges) throw new Error(`Not an ontology_layer file: ${path}`);
  return raw;
}

// ---- Human significance worksheet -------------------------------------------
// The operational handoff: for every subject, the AI-detected observation is
// shown, then the empty prompts a human must answer to lift the record above
// the escalation floor (§5) and open Rungs 2–4.
function worksheet(run, manifest) {
  const L = [];
  L.push("# Ask About Korea — Human Significance Worksheet");
  L.push("");
  L.push("> Generated by the interpretation engine. Every prompt below is a **human-owned**");
  L.push("> field under the Human–AI boundary (§12). The engine has done the detection;");
  L.push("> significance, judgment, and system design are yours to write.");
  L.push("");
  L.push(`- Source: \`${run.meta.generatedFrom ?? "—"}\``);
  L.push(`- Subjects: **${run.meta.subjects}**  ·  Escalation floor: **Level ${run.meta.floor}** (§5)`);
  L.push(`- Significance owed: **${manifest.totals.significanceOwed}** fields  ·  answered: ${manifest.totals.significanceAnswered}`);
  L.push("");
  L.push("## Dataset-level — Frame competition (§7)");
  L.push(`AI detection: ${run.frameCompetition.detected.value}`);
  L.push("");
  L.push("| Rank | Frame (perception) | Attention share |");
  L.push("|---|---|---|");
  run.frameCompetition.ranking.forEach((f, i) => L.push(`| ${i + 1} | ${f.label} | ${f.share}% |`));
  L.push("");
  L.push(`- [ ] **Interpretation (human):** ${run.frameCompetition.interpretation.prompt}`);
  L.push("");
  L.push("---");
  L.push("");
  L.push("## Per-subject significance");

  for (const rec of run.records) {
    L.push("");
    L.push(`### ${rec.subject.label}  \`${rec.subject.id}\``);
    L.push(`- **L1 · Observation (AI):** ${rec.ladder.L1_observation.value.value}`);
    L.push(`- **Systemic map (AI):** ${rec.lenses.systemic.detected.value}`);
    L.push(`- **Persistence (AI):** ${rec.questionToSystem.detected.value}`);
    L.push("");
    L.push("**Lenses — supply the judgment (§4):**");
    for (const lens of LENSES) {
      const f = rec.lenses[lens.key];
      L.push(`- [ ] *${lens.id} ${lens.rule}* — ${f.judgment.prompt}`);
    }
    L.push("");
    L.push("**Escalation ladder — lift above the floor (§5):**");
    for (const r of LADDER) {
      if (r.author === "ai") continue;
      const flag = r.level === run.meta.floor ? "  ⟂ floor" : "";
      L.push(`- [ ] **L${r.level} ${r.title}${flag}:** ${rec.ladder[r.key].value.prompt}`);
    }
    L.push("");
    L.push(`- [ ] **Question→System (§6):** ${rec.questionToSystem.missingSystem.prompt}`);
    L.push("");
    L.push("**Three-output gate — analysis is incomplete without these (§13):**");
    for (const o of OUTPUT_GATE) L.push(`- [ ] **${o.key}** — ${rec.outputs[o.key].value.prompt}`);
  }
  L.push("");
  L.push("---");
  L.push("");
  L.push("## Circulation (§9/§14) — regenerate the cycle");
  L.push(`- Unclustered questions (AI): ${run.circulation.unclustered.value}`);
  L.push(`- Thin-coverage concepts (AI): ${(run.circulation.thinCoverage.value ?? []).map((c) => c.label).join(", ") || "—"}`);
  L.push(`- [ ] **New questions (human):** ${run.circulation.newQuestions.prompt}`);
  L.push("");
  return L.join("\n");
}

function main() {
  const input = process.argv[2] ? resolve(process.cwd(), process.argv[2]) : DEFAULT_INPUT;
  const ontology = loadOntology(input);

  const run = interpret(ontology);            // asserts boundary per record internally
  const manifest = generateResearch(run);

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(resolve(OUT_DIR, "interpretation.json"), JSON.stringify(run, null, 2));
  writeFileSync(resolve(OUT_DIR, "research-manifest.json"), JSON.stringify(manifest, null, 2));
  writeFileSync(resolve(OUT_DIR, "human-worksheet.md"), worksheet(run, manifest));

  console.log("Ask About Korea — interpretation engine");
  console.log("  input   :", input.replace(ROOT + "/", ""));
  console.log("  subjects:", run.meta.subjects);
  console.log("  frame   :", run.frameCompetition.detected.value);
  console.log("  rungs   :",
    manifest.rungs.map((r) => `R${r.rung}:${r.machineReady ? "ready" : `owes ${r.readiness.owed}`}`).join("  "));
  console.log("  boundary: all significance fields left human-owned (§12) — OK");
  console.log("  wrote   : reasoning/output/{interpretation.json, research-manifest.json, human-worksheet.md}");
}

main();
