// Generates collection_report.md from the run metrics.

function countBy(rows, key) {
  const m = new Map();
  for (const r of rows) m.set(r[key], (m.get(r[key]) || 0) + 1);
  return m;
}

function table(headers, rows) {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
  return `${head}\n${sep}\n${body}`;
}

export function buildReport({
  meta,
  rawAll,
  inScope,
  quarantined,
  canonicals,
}) {
  const bySource = countBy(rawAll, "sourcePlatform");
  const byRegion = countBy(rawAll, "countryRegion");
  const byLang = countBy(rawAll, "language");

  const dedupRatio = canonicals.length
    ? (inScope.length / canonicals.length).toFixed(2)
    : "—";

  const crossMarket = canonicals.filter((c) => c.coverage.countries > 1);
  const crossSource = canonicals.filter((c) => c.coverage.sources > 1);

  const topRows = canonicals.slice(0, 15).map((c) => [
    c.canonicalText.replace(/\|/g, "\\|"),
    c.frequencyIndicator.toFixed(3),
    c.coverage.countries,
    c.coverage.sources,
    c.coverage.variants,
    c.countries.join(" "),
  ]);

  const crossRows = crossMarket
    .slice(0, 10)
    .map((c) => [
      c.canonicalText.replace(/\|/g, "\\|"),
      c.countries.join(" "),
      c.sources.join(" "),
      c.coverage.variants,
    ]);

  const quarantineByReason = countBy(quarantined, "quarantineReason");
  const quarantineRows = Array.from(quarantineByReason.entries()).map(
    ([reason, n]) => [reason, n]
  );
  const quarantineExamples = quarantined
    .slice(0, 6)
    .map((q) => [q.questionText.replace(/\|/g, "\\|"), q.quarantineReason]);

  return `# Ask About Korea — Collection Report

_Generated by \`collect/\` · tool version \`${meta.version}\`_

## Run metadata

- **Mode:** ${meta.mode}${meta.modeNote ? ` — ${meta.modeNote}` : ""}
- **Date:** ${meta.date}
- **Locales:** ${meta.locales.join(", ")}
- **Sources:** Google Autocomplete, Google People Also Ask
- **Autocomplete seed queries attempted:** ${meta.autocompleteAttempts}
- **PAA seed queries attempted:** ${meta.paaAttempts}${meta.paaSkippedNoKey ? " (skipped: no SERPAPI_KEY)" : ""}

> This is a **methodology-validation run**, not a scale run. Its purpose is to
> confirm the collect → normalize → deduplicate → canonicalize pipeline works on
> realistic data across all launch locales.

## Pipeline funnel

${table(
  ["Stage", "Count"],
  [
    ["Raw collected", rawAll.length],
    ["Quarantined (spam / off-topic)", quarantined.length],
    ["In scope", inScope.length],
    ["Canonical questions", canonicals.length],
  ]
)}

**Deduplication ratio:** ${dedupRatio} : 1 (in-scope → canonical).
Cross-locale duplication drives this above the single-market pilot ratio — the
duplicates are the market-coverage signal, not waste.

## Distribution

**By source**

${table(["Source", "Raw records"], Array.from(bySource.entries()))}

**By country / region**

${table(["Region", "Raw records"], Array.from(byRegion.entries()))}

**By language**

${table(["Language", "Raw records"], Array.from(byLang.entries()))}

## Top canonical questions (by relative salience)

${table(
  ["Canonical question", "Salience", "Markets", "Sources", "Variants", "Where"],
  topRows
)}

## Cross-market questions (surfaced in >1 locale)

${crossMarket.length} of ${canonicals.length} canonical questions appeared in more
than one market; ${crossSource.length} appeared on more than one source.

${table(["Canonical question", "Markets", "Sources", "Variants"], crossRows)}

## Quarantine (audited, not deleted)

${
  quarantined.length === 0
    ? "No items were quarantined in this run."
    : table(["Reason", "Count"], quarantineRows) +
      "\n\n_Examples:_\n\n" +
      table(["Item", "Reason"], quarantineExamples)
}

## Reproducibility

- **Offline mode** is fully deterministic: it reads \`fixtures/*.json\` and applies
  the same normalization and merge rules every run.
- **Live mode** (\`node run.mjs --mode live\`) queries the unofficial Google
  Autocomplete endpoint (free) and, if \`SERPAPI_KEY\` is set, People Also Ask via
  SERP API. It requires a network on which those hosts are reachable.
- Every canonical question records its \`variantIds\`, so each merge can be traced
  back to the exact raw records that produced it.

## Notes & limitations

- The country signal is the **question surface served to each locale**, set via
  \`gl\`/\`hl\` — not per-person geodata. Age and gender are out of scope.
- Frequency is a **relative** indicator; no source provides true volume.
- Near-duplicate merging here is lexical (content-token signature + Jaccard) for
  full transparency; production may substitute embeddings.
- Korean tokenization is lightweight (particle stripping); it is sufficient for
  Stage 100 but not linguistically complete.
`;
}
